foreground #e2e3d8
background #12140e
selection_foreground #1f3701
selection_background #b1d18a

cursor #b1d18a
cursor_text_color #1f3701

url_color #a0d0cc

active_border_color #b1d18a
inactive_border_color #44483d
bell_border_color #ffb4ab

wayland_titlebar_color system
macos_titlebar_color system

active_tab_foreground #1f3701
active_tab_background #b1d18a
inactive_tab_foreground #c5c8ba
inactive_tab_background #1e201a
tab_bar_background #12140e

mark1_foreground #1f3701
mark1_background #b1d18a
mark2_foreground #2a331e
mark2_background #bfcbad
mark3_foreground #003735
mark3_background #a0d0cc

color0 #33362e
color8 #8e9285

color1 #ffb4ab
color9 #ffb4ab

color2 #b1d18a
color10 #b1d18a

color3 #bfcbad
color11 #bfcbad

color4 #a0d0cc
color12 #a0d0cc

color5 #b1d18a
color13 #b1d18a

color6 #bfcbad
color14 #bfcbad

color7 #c5c8ba
color15 #e2e3d8
