foreground #e5e1e9
background #131318
selection_foreground #2c2a60
selection_background #c3c0ff

cursor #c3c0ff
cursor_text_color #2c2a60

url_color #eab9d1

active_border_color #c3c0ff
inactive_border_color #47464f
bell_border_color #ffb4ab

wayland_titlebar_color system
macos_titlebar_color system

active_tab_foreground #2c2a60
active_tab_background #c3c0ff
inactive_tab_foreground #c8c5d0
inactive_tab_background #201f25
tab_bar_background #131318

mark1_foreground #2c2a60
mark1_background #c3c0ff
mark2_foreground #2f2e42
mark2_background #c7c4dd
mark3_foreground #472639
mark3_background #eab9d1

color0 #35343a
color8 #928f9a

color1 #ffb4ab
color9 #ffb4ab

color2 #c3c0ff
color10 #c3c0ff

color3 #c7c4dd
color11 #c7c4dd

color4 #eab9d1
color12 #eab9d1

color5 #c3c0ff
color13 #c3c0ff

color6 #c7c4dd
color14 #c7c4dd

color7 #c8c5d0
color15 #e5e1e9
